# Generated by Django 5.2.6 on 2025-12-31 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_product_delete_orderitem'),
        ('product', '0002_operator_productionline_requirements_productiontask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال بازرسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_correction', 'نیاز به اصلاح')], default='pending', max_length=20, verbose_name='وضعیت بازرسی')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازرسی')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='توضیحات بازرس')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد (در صورت وجود)')),
                ('corrected', models.BooleanField(default=False, verbose_name='اصلاح شده')),
                ('correction_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اصلاح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_logs', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'لاگ بازرسی',
                'verbose_name_plural': 'لاگ\u200cهای بازرسی',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True, verbose_name='کد کارت تولید')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کارت تولید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_approval', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('in_production', 'در حال تولید'), ('paused', 'متوقف شده'), ('completed', 'تکمیل شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت کارت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت تولید')),
                ('quantity_to_produce', models.PositiveIntegerField(default=1, verbose_name='تعداد مورد نیاز')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='زمان تخمینی تولید (ساعت)')),
                ('scheduled_start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع برنامه\u200cریزی شده')),
                ('scheduled_end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان برنامه\u200cریزی شده')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان واقعی')),
                ('current_progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت (%)')),
                ('required_materials', models.JSONField(blank=True, default=list, verbose_name='لیست مواد اولیه مورد نیاز')),
                ('required_components', models.JSONField(blank=True, default=list, verbose_name='لیست قطعات مورد نیاز')),
                ('required_tools', models.JSONField(blank=True, default=list, verbose_name='لیست ابزار مورد نیاز')),
                ('production_standards', models.TextField(blank=True, verbose_name='استانداردهای تولید')),
                ('special_instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cهای ویژه')),
                ('qc_required', models.BooleanField(default=True, verbose_name='نیاز به کنترل کیفیت دارد')),
                ('qc_checkpoints', models.PositiveIntegerField(default=1, verbose_name='تعداد نقاط کنترل کیفیت')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='فایل\u200cهای پیوست')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('requirements_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cards', to='product.requirementsproducts', verbose_name='محصول و الزامات مرتبط')),
            ],
            options={
                'verbose_name': 'کارت تولید',
                'verbose_name_plural': 'کارت\u200cهای تولید',
                'ordering': ['-priority', 'scheduled_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='نام ماده اولیه')),
                ('material_code', models.CharField(max_length=50, verbose_name='کد ماده')),
                ('unit', models.CharField(max_length=20, verbose_name='واحد اندازه\u200cگیری')),
                ('estimated_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخمینی')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار مصرف واقعی')),
                ('consumption_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصرف')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.operator', verbose_name='مصرف شده توسط')),
                ('production_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='QC.productioncard', verbose_name='کارت تولید')),
            ],
            options={
                'verbose_name': 'مصرف مواد اولیه',
                'verbose_name_plural': 'مصرف مواد اولیه',
            },
        ),
        migrations.CreateModel(
            name='QualityControlExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('department', models.CharField(max_length=100, verbose_name='بخش/واحد کنترل کیفیت')),
                ('qualification_level', models.CharField(choices=[('basic', 'کارشناس پایه'), ('senior', 'کارشناس ارشد'), ('supervisor', 'سرپرست'), ('manager', 'مدیر کنترل کیفیت')], default='basic', max_length=20, verbose_name='سطح صلاحیت')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص ویژه')),
                ('inspected_products_count', models.PositiveIntegerField(default=0, verbose_name='تعداد محصولات بازرسی شده')),
                ('approval_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='نرخ تایید (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سیستم')),
            ],
            options={
                'verbose_name': 'کارشناس کنترل کیفیت',
                'verbose_name_plural': 'کارشناسان کنترل کیفیت',
                'ordering': ['-qualification_level', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='QCStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام استاندارد')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد استاندارد')),
                ('description', models.TextField(verbose_name='توضیحات استاندارد')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QC.qualitycontrolexpert', verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'استاندارد QC',
                'verbose_name_plural': 'استانداردهای QC',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QCHistoryCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('inspected_orders', models.ManyToManyField(blank=True, related_name='QC_inspections', to='order.order', verbose_name='سفارش\u200cهای بازرسی شده')),
                ('inspection_logs', models.ManyToManyField(blank=True, related_name='qc_expert_logs', to='QC.inspectionlog', verbose_name='لاگ\u200cهای بازرسی')),
                ('qc_expert', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qc_history', to='QC.qualitycontrolexpert', verbose_name='کارشناس کنترل کیفیت')),
            ],
            options={
                'verbose_name': 'تاریخچه بازرسی QC',
                'verbose_name_plural': 'تاریخچه\u200cهای بازرسی QC',
            },
        ),
        migrations.AddField(
            model_name='productioncard',
            name='approved_by_qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_approved_production_cards', to='QC.qualitycontrolexpert', verbose_name='تأیید شده توسط کنترل کیفیت'),
        ),
        migrations.AddField(
            model_name='productioncard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_cards', to='QC.qualitycontrolexpert', verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to='QC.qualitycontrolexpert', verbose_name='بازرس'),
        ),
        migrations.CreateModel(
            name='ProductionCardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('status_change', 'تغییر وضعیت'), ('progress_update', 'به\u200cروزرسانی پیشرفت'), ('operator_assignment', 'اختصاص اپراتور'), ('material_usage', 'مصرف مواد'), ('quality_check', 'کنترل کیفیت'), ('note_added', 'افزودن یادداشت'), ('file_uploaded', 'آپلود فایل'), ('time_adjustment', 'تغییر زمان')], max_length=20, verbose_name='نوع رویداد')),
                ('description', models.TextField(verbose_name='توضیحات رویداد')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انجام')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام شده توسط')),
                ('production_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='QC.productioncard', verbose_name='کارت تولید')),
            ],
            options={
                'verbose_name': 'لاگ کارت تولید',
                'verbose_name_plural': 'لاگ\u200cهای کارت تولید',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['production_card', 'performed_at'], name='QC_producti_product_062e8d_idx'), models.Index(fields=['log_type'], name='QC_producti_log_typ_08301a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productioncard',
            index=models.Index(fields=['card_code'], name='QC_producti_card_co_4f90af_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncard',
            index=models.Index(fields=['status'], name='QC_producti_status_9dcded_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncard',
            index=models.Index(fields=['priority'], name='QC_producti_priorit_a38de5_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncard',
            index=models.Index(fields=['scheduled_start_date'], name='QC_producti_schedul_ccd84b_idx'),
        ),
    ]
