# Generated by Django 6.0 on 2026-01-01 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCardQCInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_code', models.CharField(max_length=50, unique=True, verbose_name='کد بازرسی')),
                ('inspection_type', models.CharField(choices=[('initial', 'بازرسی اولیه'), ('in_process', 'بازرسی حین تولید'), ('final', 'بازرسی نهایی'), ('random', 'بازرسی تصادفی'), ('special', 'بازرسی ویژه')], default='in_process', max_length=20, verbose_name='نوع بازرسی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بازرسی'), ('in_progress', 'در حال بازرسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('needs_correction', 'نیاز به اصلاح'), ('re_inspection', 'بازرسی مجدد')], default='pending', max_length=20, verbose_name='وضعیت بازرسی')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده بازرسی')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان واقعی')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز کلی')),
                ('passed_items', models.PositiveIntegerField(default=0, verbose_name='تعداد موارد تأیید شده')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='تعداد موارد رد شده')),
                ('total_items_checked', models.PositiveIntegerField(default=0, verbose_name='تعداد کل موارد بررسی شده')),
                ('checklist_items', models.JSONField(blank=True, default=list, verbose_name='اقلام چک لیست')),
                ('test_results', models.JSONField(blank=True, default=list, verbose_name='نتایج آزمون\u200cها')),
                ('measurements', models.JSONField(blank=True, default=list, verbose_name='اندازه\u200cگیری\u200cها')),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='qc_reports/production_cards/', verbose_name='گزارش بازرسی')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='عکس\u200cهای بازرسی')),
                ('inspector_comments', models.TextField(blank=True, verbose_name='نظرات بازرس')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد (در صورت وجود)')),
                ('correction_instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cهای اصلاح')),
                ('needs_correction', models.BooleanField(default=False, verbose_name='نیاز به اصلاح دارد')),
                ('corrected', models.BooleanField(default=False, verbose_name='اصلاح شده')),
                ('correction_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اصلاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'بازرسی کارت تولید',
                'verbose_name_plural': 'بازرسی\u200cهای کارت تولید',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.RemoveField(
            model_name='materialconsumption',
            name='consumed_by',
        ),
        migrations.RemoveField(
            model_name='materialconsumption',
            name='production_card',
        ),
        migrations.RemoveIndex(
            model_name='productioncardlog',
            name='QC_producti_product_062e8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncardlog',
            name='QC_producti_log_typ_08301a_idx',
        ),
        migrations.RemoveField(
            model_name='qcstandard',
            name='created_by',
        ),
        migrations.AddField(
            model_name='qchistorycreator',
            name='inspected_cart',
            field=models.ManyToManyField(related_name='inspected_cart_p_cart', to='QC.productioncard'),
        ),
        migrations.RemoveField(
            model_name='productioncard',
            name='approved_by_qa',
        ),
        migrations.AlterField(
            model_name='productioncard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_cards', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='productioncardqcinspection',
            name='approved_by_qc_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_card_inspections', to='QC.qualitycontrolexpert', verbose_name='تأیید شده توسط مدیر QC'),
        ),
        migrations.AddField(
            model_name='productioncardqcinspection',
            name='inspector',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_inspections', to='QC.qualitycontrolexpert', verbose_name='بازرس QC'),
        ),
        migrations.AddField(
            model_name='productioncardqcinspection',
            name='production_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='QC.productioncard', verbose_name='کارت تولید'),
        ),
        migrations.DeleteModel(
            name='MaterialConsumption',
        ),
        migrations.RemoveField(
            model_name='productioncardlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='productioncardlog',
            name='production_card',
        ),
        migrations.DeleteModel(
            name='QCStandard',
        ),
        migrations.AddField(
            model_name='productioncard',
            name='approved_by_qa',
            field=models.ManyToManyField(blank=True, null=True, related_name='qa_approved_production_cards', to='QC.qualitycontrolexpert', verbose_name='تأیید شده توسط کنترل کیفیت'),
        ),
        migrations.AddIndex(
            model_name='productioncardqcinspection',
            index=models.Index(fields=['inspection_code'], name='QC_producti_inspect_ebc5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncardqcinspection',
            index=models.Index(fields=['status'], name='QC_producti_status_0d326d_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncardqcinspection',
            index=models.Index(fields=['production_card', 'status'], name='QC_producti_product_f2306c_idx'),
        ),
        migrations.DeleteModel(
            name='ProductionCardLog',
        ),
    ]
