# Generated by Django 6.0 on 2026-01-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_productioncardqcinspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncard',
            name='approved_by_qa',
            field=models.ManyToManyField(blank=True, related_name='qa_approved_production_cards', to='QC.qualitycontrolexpert', verbose_name='تأیید شده توسط کنترل کیفیت'),
        ),
    ]
