# Generated by Django 4.2.27 on 2025-12-29 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_product_delete_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('branch', models.CharField(max_length=100, verbose_name='شعبه/واحد فروش')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع فروش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارشناس فروش',
                'verbose_name_plural': 'کارشناسان فروش',
            },
        ),
        migrations.CreateModel(
            name='OrderHistoryCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to='order.order')),
                ('saleser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderHistory', to='Sales.salesexpert')),
            ],
        ),
    ]
