# Generated by Django 6.0 on 2026-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesexpert',
            name='customer_satisfaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع فروش'),
        ),
        migrations.AddField(
            model_name='salesexpert',
            name='mount_sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع فروش'),
        ),
        migrations.AddField(
            model_name='salesexpert',
            name='product_added',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع فروش'),
        ),
        migrations.AddField(
            model_name='salesexpert',
            name='total_sales_product_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع فروش'),
        ),
    ]
