# Generated by Django 5.2.6 on 2025-12-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
        ('order', '0002_order_product_delete_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='customer_family',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Sales.salesexpert'),
            preserve_default=False,
        ),
    ]
