# Generated by Django 6.0 on 2026-01-01 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QC', '0003_alter_productioncard_approved_by_qa'),
        ('order', '0003_rename_first_name_order_customer_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=50, unique=True, verbose_name='کد ایستگاه کاری')),
                ('name', models.CharField(max_length=200, verbose_name='نام ایستگاه کاری')),
                ('station_type', models.CharField(choices=[('incoming_inspection', 'بازرسی مواد ورودی'), ('in_process', 'بازرسی حین فرآیند'), ('final_inspection', 'بازرسی نهایی'), ('packaging', 'بازرسی بسته\u200cبندی'), ('laboratory', 'آزمایشگاه'), ('calibration', 'کالیبراسیون'), ('warehouse', 'انبار'), ('shipping', 'بارگیری')], max_length=50, verbose_name='نوع ایستگاه')),
                ('location', models.CharField(max_length=300, verbose_name='مکان ایستگاه')),
                ('department', models.CharField(max_length=100, verbose_name='دپارتمان/بخش')),
                ('equipments', models.JSONField(blank=True, default=list, verbose_name='تجهیزات موجود')),
                ('tools', models.JSONField(blank=True, default=list, verbose_name='ابزارهای اندازه\u200cگیری')),
                ('max_daily_capacity', models.PositiveIntegerField(default=50, verbose_name='ظرفیت روزانه (تعداد بازرسی)')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='ساعات کاری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('maintenance', 'در حال تعمیر'), ('calibration_due', 'نیاز به کالیبراسیون')], default='active', max_length=20, verbose_name='وضعیت ایستگاه')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس است')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workstations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('qc_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_workstations', to='QC.qualitycontrolexpert', verbose_name='مسئول QC ایستگاه')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workstations', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست ایستگاه')),
            ],
            options={
                'verbose_name': 'ایستگاه کاری',
                'verbose_name_plural': 'ایستگاه\u200cهای کاری',
                'ordering': ['department', 'station_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkStationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=50, unique=True, verbose_name='کد گزارش')),
                ('report_type', models.CharField(choices=[('routine_inspection', 'بازرسی معمول'), ('non_conformity', 'عدم انطباق'), ('calibration', 'کالیبراسیون'), ('maintenance', 'تعمیرات'), ('incident', 'حادثه'), ('audit', 'بازرسی داخلی'), ('improvement', 'اقدام بهبود')], max_length=30, verbose_name='نوع گزارش')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان گزارش')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='اولویت')),
                ('description', models.TextField(verbose_name='شرح گزارش')),
                ('observations', models.TextField(blank=True, verbose_name='مشاهدات')),
                ('findings', models.JSONField(blank=True, default=list, verbose_name='یافته\u200cها')),
                ('measurements', models.JSONField(blank=True, default=list, verbose_name='اندازه\u200cگیری\u200cها')),
                ('test_results', models.JSONField(blank=True, default=list, verbose_name='نتایج آزمایش')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='عکس\u200cها')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='مستندات ضمیمه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('under_review', 'در حال بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('action_required', 'نیاز به اقدام'), ('completed', 'تکمیل شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت گزارش')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='اقدامات اصلاحی')),
                ('preventive_actions', models.TextField(blank=True, verbose_name='اقدامات پیشگیرانه')),
                ('action_deadline', models.DateTimeField(blank=True, null=True, verbose_name='ددلاین اقدام')),
                ('review_comments', models.TextField(blank=True, verbose_name='نظرات بررسی')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ گزارش')),
                ('inspection_start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع بازرسی')),
                ('inspection_end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان بازرسی')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='محرمانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('action_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_responsible_reports', to=settings.AUTH_USER_MODEL, verbose_name='مسئول اقدام')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to='QC.qualitycontrolexpert', verbose_name='تأیید شده توسط')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_reports', to='order.order', verbose_name='سفارش مرتبط')),
                ('related_production_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_reports', to='QC.productioncard', verbose_name='کارت تولید مرتبط')),
                ('related_qc_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_reports', to='QC.productioncardqcinspection', verbose_name='بازرسی QC مرتبط')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_reports', to='QC.qualitycontrolexpert', verbose_name='گزارش\u200cدهنده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='QC.qualitycontrolexpert', verbose_name='بررسی شده توسط')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_reports', to='report.workstation', verbose_name='ایستگاه کاری')),
            ],
            options={
                'verbose_name': 'گزارش ایستگاه کاری',
                'verbose_name_plural': 'گزارش\u200cهای ایستگاه کاری',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkStationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('capacity_warning', 'هشدار ظرفیت'), ('maintenance_due', 'تعمیرات دوره\u200cای'), ('calibration_due', 'کالیبراسیون دوره\u200cای'), ('equipment_failure', 'خرابی تجهیزات'), ('safety_issue', 'مسئله ایمنی'), ('quality_issue', 'مسئله کیفیت'), ('urgent_report', 'گزارش فوری'), ('deadline_approaching', 'نزدیک شدن ددلاین')], max_length=50, verbose_name='نوع اعلان')),
                ('alert_level', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('error', 'خطا'), ('critical', 'بحرانی')], max_length=20, verbose_name='سطح اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اعلان')),
                ('description', models.TextField(verbose_name='توضیحات اعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان فعال شدن')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رفع')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای رفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='report.workstation', verbose_name='ایستگاه کاری')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='report.workstationreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'اعلان ایستگاه کاری',
                'verbose_name_plural': 'اعلان\u200cهای ایستگاه کاری',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkStationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'ورود به ایستگاه'), ('logout', 'خروج از ایستگاه'), ('report_created', 'ایجاد گزارش'), ('report_updated', 'ویرایش گزارش'), ('report_submitted', 'ثبت گزارش'), ('report_reviewed', 'بررسی گزارش'), ('report_approved', 'تأیید گزارش'), ('calibration_started', 'شروع کالیبراسیون'), ('calibration_completed', 'اتمام کالیبراسیون'), ('maintenance_started', 'شروع تعمیرات'), ('maintenance_completed', 'اتمام تعمیرات'), ('equipment_used', 'استفاده از تجهیزات'), ('alert_triggered', 'اعلان فعال شد'), ('status_changed', 'تغییر وضعیت')], max_length=50, verbose_name='نوع فعالیت')),
                ('description', models.TextField(verbose_name='توضیحات فعالیت')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات فعالیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('qc_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QC.qualitycontrolexpert', verbose_name='کارشناس QC')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='report.workstation', verbose_name='ایستگاه کاری')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='report.workstationreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت ایستگاه',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت ایستگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['station_code'], name='report_work_station_6b15f6_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['station_type'], name='report_work_station_9be12c_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['status'], name='report_work_status_1e5ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['department'], name='report_work_departm_9ad682_idx'),
        ),
        migrations.AddIndex(
            model_name='workstationreport',
            index=models.Index(fields=['report_code'], name='report_work_report__52ee06_idx'),
        ),
        migrations.AddIndex(
            model_name='workstationreport',
            index=models.Index(fields=['status'], name='report_work_status_ed301d_idx'),
        ),
        migrations.AddIndex(
            model_name='workstationreport',
            index=models.Index(fields=['workstation', 'report_date'], name='report_work_worksta_1030c3_idx'),
        ),
        migrations.AddIndex(
            model_name='workstationreport',
            index=models.Index(fields=['reporter', 'status'], name='report_work_reporte_e15447_idx'),
        ),
        migrations.AddIndex(
            model_name='workstationreport',
            index=models.Index(fields=['priority', 'is_urgent'], name='report_work_priorit_daa7d4_idx'),
        ),
    ]
