# Generated by Django 5.2.6 on 2025-12-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_product_delete_orderitem'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=122)),
                ('family', models.CharField(max_length=122)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خط تولید')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='محل استقرار')),
                ('capacity', models.PositiveIntegerField(default=5, verbose_name='ظرفیت همزمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خط تولید',
                'verbose_name_plural': 'خطوط تولید',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('processing', 'در حال تولید'), ('qc_pending', 'در انتظار QC'), ('qc_rejected', 'رد شده در QC'), ('completed', 'تکمیل شده')], default='waiting', max_length=20, verbose_name='وضعیت فعلی')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='تاریخچه تغییرات')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_task', to='order.order', verbose_name='سفارش')),
                ('production_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_tasks', to='product.productionline', verbose_name='خط تولید اختصاص یافته')),
            ],
            options={
                'verbose_name': 'فرآیند تولید',
                'verbose_name_plural': 'فرآیندهای تولید',
            },
        ),
        migrations.CreateModel(
            name='RequirementsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orpertors', models.ManyToManyField(to='product.operator')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Requirements_Products', to='product.product')),
                ('product_timeline', models.ManyToManyField(to='product.productionline')),
                ('requirements', models.ManyToManyField(to='product.requirements')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
